---
- name: ensure apt cache is up to date
  apt: update_cache=yes

- name: ensure packages are installed
  apt: name={{item}}
  with_items:
      - acl
      - git 
      - libpq-dev
      - python3-dev
      - python3-pip